version: "3.9"

services:
  
  app:
    build:
      args:
        enable_xdebug: ${DOCKER_PHP_ENABLE_XDEBUG}
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/app
    volumes:
      - ./:/var/www
    networks:
      - backend

  db:
    image: postgres
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
    networks:
      - backend

  server:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./:/var/www/
      - ./docker-compose/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - db
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend


networks:
  backend:
    driver: bridge