apiVersion: v1
kind: Deployment
metadata:
  name: parse-this-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parse-this-news
  template:
    metadata:
      labels:
        app: parse-this-news
    spec:
      containers:
        # - name: code
        #   image: parse-this-news:v0.1.0
        #   # env:
        #   # ports:
        #   #   - containerPort: 8000
        #   volumeMounts:
        #     - name: code
        #       mountPath: /var/www
        - name: server
          image: nginx:stable-alpine
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: code
              mountPath: /var/www
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: code
          hostPath:
          # mounted directory on minikube
            path: /app
        
        # Add the ConfigMap we declared above as a volume for the pod
        - name: nginx-config-volume
          configMap:
            name: nginx-config
